/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package findex;

import org.junit.Test;

import java.util.Collections;

import static org.junit.Assert.*;

public class FindexTest {
    @Test public void someLibraryMethodReturnsTrue() {
//        Findex classUnderTest = new Findex(Collections.emptyList(), "~/Desktop");
//        assertTrue("someLibraryMethod should return 'true'",
//                classUnderTest.someLibraryMethod());
    }
}
